=== CatalinRapeanu/Proiect3_BazeDeDate/src/xml/bauturi.dtd
<!ELEMENT root (bautura)+>
<!ATTLIST root
xmlns CDATA #FIXED">

<!ELEMENT bautura (id, nume, imagine, ingrediente, tip_bautura, pret, edit, view, delete, confirm, upload, back)>
<!ATTLIST bautura
xmlns CDATA #FIXED">

<!ELEMENT id (#PCDATA)>
<!ATTLIST id
xmlns CDATA #FIXED">

<!ELEMENT nume (#PCDATA)>
<!ATTLIST nume
xmlns CDATA #FIXED">

<!ELEMENT imagine (#PCDATA)>
<!ATTLIST imagine
xmlns CDATA #FIXED">

<!ELEMENT ingrediente (#PCDATA)>
<!ATTLIST ingrediente
xmlns CDATA #FIXED">

<!ELEMENT tip_bautura (#PCDATA)>
<!ATTLIST tip_bautura
xmlns CDATA #FIXED">

<!ELEMENT pret (#PCDATA)>
<!ATTLIST pret
xmlns CDATA #FIXED">

<!ELEMENT edit (#PCDATA)>
<!ATTLIST edit
xmlns CDATA #FIXED">

<!ELEMENT view (#PCDATA)>
<!ATTLIST view
xmlns CDATA #FIXED">

<!ELEMENT delete (#PCDATA)>
<!ATTLIST delete
xmlns CDATA #FIXED">

<!ELEMENT confirm (#PCDATA)>
<!ATTLIST confirm
xmlns CDATA #FIXED">

<!ELEMENT upload (#PCDATA)>
<!ATTLIST upload
xmlns CDATA #FIXED">

<!ELEMENT back (#PCDATA)>
<!ATTLIST back
xmlns CDATA #FIXED">

=== CatalinRapeanu/Proiect3_BazeDeDate/src/xml/bauturi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "bauturi.dtd">
<root> 
<bautura><id>2</id><nume>aaaaa</nume><imagine>./multimedia/pinguini.jpg</imagine><ingrediente>bbbbb</ingrediente><tip_bautura>shot</tip_bautura><pret>11</pret><edit>editimage.php?id=2</edit><view>view.php?id=2</view><delete>deleteimage.php?id=2</delete><confirm>return  confirm("Are you sure you want to delete this?")</confirm><upload>upload.php</upload><back>administrarebaza.php</back></bautura>
<bautura><id>4</id><nume>AAAAHHHHHHHHHHHHHHH</nume><imagine>./multimedia/mata.jpg</imagine><ingrediente>.........</ingrediente><tip_bautura>shot</tip_bautura><pret>21</pret><edit>editimage.php?id=4</edit><view>view.php?id=4</view><delete>deleteimage.php?id=4</delete><confirm>return  confirm("Are you sure you want to delete this?")</confirm><upload>upload.php</upload><back>administrarebaza.php</back></bautura>
<bautura><id>5</id><nume>fdfdf</nume><imagine>./multimedia/sexonthebeach.jpg</imagine><ingrediente>dfdf</ingrediente><tip_bautura>shot</tip_bautura><pret>22</pret><edit>editimage.php?id=5</edit><view>view.php?id=5</view><delete>deleteimage.php?id=5</delete><confirm>return  confirm("Are you sure you want to delete this?")</confirm><upload>upload.php</upload><back>administrarebaza.php</back></bautura>
<bautura><id>6</id><nume>dddddddd</nume><imagine>./multimedia/mata.jpg</imagine><ingrediente>dddddddd</ingrediente><tip_bautura>dddddd</tip_bautura><pret>22</pret><edit>editimage.php?id=6</edit><view>view.php?id=6</view><delete>deleteimage.php?id=6</delete><confirm>return  confirm("Are you sure you want to delete this?")</confirm><upload>upload.php</upload><back>administrarebaza.php</back></bautura>
<bautura><id>7</id><nume>sdfsdfsdf</nume><imagine>./multimedia/pisica.webp</imagine><ingrediente>sdfsddf</ingrediente><tip_bautura>sadasd</tip_bautura><pret>12</pret><edit>editimage.php?id=7</edit><view>view.php?id=7</view><delete>deleteimage.php?id=7</delete><confirm>return  confirm("Are you sure you want to delete this?")</confirm><upload>upload.php</upload><back>administrarebaza.php</back></bautura>
</root>
