=== CatalinRapeanu/Proiect3_BazeDeDate/src/xml/conturi.dtd
<!ELEMENT root (cont)+>
<!ATTLIST root
xmlns CDATA #FIXED">

<!ELEMENT cont (id, username, password, user_type, edit, delete, confirm)>
<!ATTLIST cont
xmlns CDATA #FIXED">

<!ELEMENT id (#PCDATA)>
<!ATTLIST id
xmlns CDATA #FIXED">

<!ELEMENT username (#PCDATA)>
<!ATTLIST username
xmlns CDATA #FIXED">

<!ELEMENT password (#PCDATA)>
<!ATTLIST password
xmlns CDATA #FIXED">

<!ELEMENT user_type (#PCDATA)>
<!ATTLIST user_type
xmlns CDATA #FIXED">

<!ELEMENT edit (#PCDATA)>
<!ATTLIST edit
xmlns CDATA #FIXED">

<!ELEMENT delete (#PCDATA)>
<!ATTLIST delete
xmlns CDATA #FIXED">

<!ELEMENT confirm (#PCDATA)>
<!ATTLIST confirm
xmlns CDATA #FIXED">

=== CatalinRapeanu/Proiect3_BazeDeDate/src/xml/conturi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "conturi.dtd">
<root> 
<cont><id>2</id><username>PLAAAANG:(</username><password>ACUMA</password><user_type>admin</user_type><edit>edit.php?id=2</edit><delete>delete.php?id=2</delete><confirm>return  confirm("Are you sure you want to delete this?")</confirm></cont> 
<cont><id>3</id><username>catalin</username><password>forthewin</password><user_type>admin</user_type><edit>edit.php?id=3</edit><delete>delete.php?id=3</delete><confirm>return  confirm("Are you sure you want to delete this?")</confirm></cont>
<cont><id>4</id><username>marean</username><password>12345</password><user_type>user</user_type><edit>edit.php?id=4</edit><delete>delete.php?id=4</delete><confirm>return  confirm("Are you sure you want to delete this?")</confirm></cont>
<cont><id>5</id><username>qwerty</username><password>12345</password><user_type>user</user_type><edit>edit.php?id=5</edit><delete>delete.php?id=5</delete><confirm>return  confirm("Are you sure you want to delete this?")</confirm></cont>
</root>
